backend:
  name: github
  repo: patrickdaveWM/evol-toi # Exemple : monpseudo/evol-toi
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages du site"
    files:
      - file: "index.html"
        label: "Page d'accueil"
        name: "index"
        fields:
          - { label: "Titre principal", name: "titre_principal", widget: "string" }
          - { label: "Texte de bienvenue", name: "texte_bienvenue", widget: "markdown" }
